title: Kint | Advanced PHP dumper
description: Zero-setup replacement for var_dump
authors:
  - Jonathan Vollebregt
baseurl: "/kint"

affix_offset: 240

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

sass:
    style: compressed
